apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
  namespace: webapps 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: git-actions-svc
subjects:
- namespace: webapps 
  kind: ServiceAccount
  name: git-actions-svc
